---
- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - mariadb
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

# - name: MySQL | Config for easy access as root user
#   template: src=mysql_root.my.cnf dest=/root/.my.cnf
#   become: true

# - name: MySQL | Config for easy access as root user
#   template: src=mysql_root.my.cnf dest={{ sys_user }}/.my.cnf
#   when: "'{{ user }}' != 'root'"

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host={{ srv_pri_ip }} state=present

